config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  devise_for :users
  root to: "home#index"
  delete '/users/:id', to: 'users#destroy', as: 'destroy_user_account'
  resources :users
  resources :lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :list_name, presence: true
  validates :list_comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

    # ログイン後のリダイレクト先
    def after_sign_in_path_for(resource)
      user_path(resource.id)
    end

  protected

  def configure_permitted_parameters
    added_profile = [ :user_id, :user_name, :email, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_profile
    devise_parameter_sanitizer.permit :account_update, keys: added_profile

    added_signin = [ :user_id, :password,]
    devise_parameter_sanitizer.permit :sign_in, keys: added_signin
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # before_action :authenticate_user!

  # def index
  # end

   def show
    @list = List.find(params[:id])
   end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  private
    def list_params
      params.require(:list).permit(:list_comment,:list_name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<header>
  <h1>リストアプリ</h1>
  <nav>
    <ul>
      <li><%= link_to '新規登録', new_user_registration_path  %></li>
      <li><%= link_to 'ログイン', new_user_session_path  %></li>
    </ul>
  </nav>
</header>
<main>
  <ul>
    <li><%= link_to '新規登録', new_user_registration_path  %></li>
    <li><%= link_to 'ログイン', new_user_session_path  %></li>
  </ul>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>リスト登録</h1>

<%= form_with model: @list, local: true do |f| %>

  <%= f.label :list_name %>
  <%= f.text_field :list_name %>

  <%= f.label :list_comment %>
  <%= f.text_field :list_comment %>

  <%= f.submit %>

<% end %>

app/views/lists/show.html.erb
<p>MyPage <%= @list.id %></p>
<p><%= @list.list_comment %></p>
<p><%= @list.list_name %></p>

app/views/users/show.html.erb
<h1>マイページ</h1>
<p>ユーザーID <%= @user.id %></p>
<p>メールアドレス <%= @user.email %></p>

<%= link_to 'リストを追加', new_list_path %>
リストを編集

<%= link_to 'プロフィールを編集', edit_user_registration_path %>

<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>

<%= link_to 'アカウントを削除', destroy_user_account_path, method: :delete, data: { confirm: '削除しますか？' } %>